let a = 10; 
let b =20; 
 a += 10; 
console.log(a); 
a = a+10; 
console.log(a); 
const sum = a+b; 
console.log(sum); 
const sub = (a-b); 
console.log(sub); 
const multiply = a*b; 
console.log(multiply); 
const division = a/b; 
console.log(division); 
const exponent = a**2; 
console.log(exponent); 
const reminder = a%4; 
console.log(reminder); 

a /= 3; 
console.log(a); 
a*= 3; 
console.log(a); 
a%=4; 
console.log(a); 